#Spring配置
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codepower?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf: 
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: cn.com.codepower.*.entity